---

- name: Get GUID as local variable
  hosts: localhost
  tasks:
    - shell: "hostname | awk -F. '{ print $2 }'"
      register: varguid

- name: Create Alpha, Beta and Common projects
  hosts: localhost
  tasks:
    - shell: "oc new-project common --display-name='Common project'"
    - shell: "oc new-project alpha --display-name='Alpha Corp'"
    - shell: "oc new-project beta --display-name='Beta Corp'"

- name: Creation of users for Alpha and Beta clients - with_list
  hosts: masters
  tasks:
  - name: four users creation
    shell: "htpasswd -b /etc/origin/master/htpasswd {{ item }} r3dh4t1!;"
    with_list:
    - amy
    - andrew
    - brian
    - betty

- name: Assign tenant users to clients groups and set group labels
  hosts: masters[0]
  tasks:
    - shell: oc adm groups new alpha amy andrew
    - shell: oc adm groups new beta brian betty
    - shell: oc adm groups new common
    - shell: oc label group alpha client=alpha
    - shell: oc label group beta client=beta
    - shell: oc label group common client=common
    - shell: oc adm policy add-role-to-group admin alpha -n alpha
    - shell: oc adm policy add-role-to-group admin beta -n beta

- name: Create clusterquota for tenant users
  hosts: localhost
  vars:
    tenants:
      - amy
      - andrew
      - brian
      - betty
  tasks:
    - name: Create single clusterquota per user
      shell: "oc create clusterquota clusterquota-\"{{ item }}\" --project-annotation-selector=openshift.io/requester=\"{{ item }}\" --hard pods=25 --hard requests.memory=6Gi --hard requests.cpu=5 --hard limits.cpu=25 --hard limits.memory=40Gi --hard configmaps=25 --hard persistentvolumeclaims=25 --hard services=25"
      with_items: "{{ tenants }}"

- name: Label nodes with appropriate clients zones
  hosts: localhost
  tasks:
    - shell: "oc label node node1.{{ varguid.stdout }}.internal zone=alpha"
    - shell: "oc label node node2.{{ varguid.stdout }}.internal zone=beta"

- name: Create template
  hosts: localhost
  tasks:
    - shell: "pwd"
      register: varpwd
    - shell: "oc create -f {{ varpwd.stdout }}/templates/project_template.yml"

- name: Reconfigure masters project template and restart OpenShift
  hosts: masters
  tasks:
  - name: Reconfigure master config 
    lineinfile:
      path: /etc/origin/master/master-config.yaml
      state: "present"
      line: "projectRequestTemplate: \"default/project-request\""
      regexp: "projectRequestTemplate.*"
  - name: restart OpenShift
    shell: "systemctl restart atomic-openshift-node"
