---
- name: clean up etc origin on nodes
  hosts: nodes
  tasks:
    - shell: "rm -rf /etc/origin" 

- name: clean up srv nfs on support nodes
  hosts: nfs
  tasks:
    - shell: "rm -rf /srv/nfs/*" 

- name: clean up kubernetes dir on localhost
  hosts: localhost
  tasks: 
    - file: 
        path: "/root/.kube"
        state: "absent"
    - file:
        path: "/root/.kube"
        state: "directory"

- name: clean up kunernetes dir on localhost
  hosts: localhost
  tasks:
    - file:
        path: "/root/pvs"
        state: "absent"
    - file:
        path: "/root/pvs"
        state: "directory"

